In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/result_uaf.csv')

In [3]:
df.head(7)

,Registration Number,Name,Semester,Teacher Name,Course Code,Course Title,Credit Hours,Mid,Assignment,Final,Practical,Total,Grade
0,2024-ag-5267,AMNA JAMIL,Spring Semester 2026,Dr. Asia Rafiq,BMS-402,ENTERPRENEURSHIP,2(2-0),9,4,19,0,32.0,A
1,2024-ag-5267,AMNA JAMIL,Spring Semester 2026,Faiz Rasool,IS-402,QURAN TRANSLATION,0(0-0),0,0,100,0,100.0,P
2,2024-ag-5267,AMNA JAMIL,Spring Semester 2026,M. Zeeshan Asaf,CS-412,Visual Programming,3(2-1),7,4,17,17,45.0,B
3,2024-ag-5267,AMNA JAMIL,Spring Semester 2026,Nabeela Ashraf,CS-410,Data Structure and Algorithms,3(2-1),5.5,4,17.5,11.5,39.0,B
4,2024-ag-5267,AMNA JAMIL,Spring Semester 2026,Rabia Munir,STAT-402,Statistics and Probability,3(2-1),6.5,4,7,12,30.0,C
5,2024-ag-5267,AMNA JAMIL,Spring Semester 2026,Wajeeha Azmat,CS-408,Database Systems,3(2-1),5.5,4,18,11,39.0,B
6,2024-ag-5267,AMNA JAMIL,Spring Semester 2026,Waseem Sajjad,CS-406,Data Communication and Networks,3(2-1),8,3,19,13,43.0,B

In [4]:
excluded_teachers = ['Dr. Asia Rafiq', 'Faiz Rasool','M. Zeeshan Asaf','Nabeela Ashraf','Rabia Munir','Wajeeha Azmat','Waseem Sajjad']

other_teachers_data = df[~df['Teacher Name'].isin(excluded_teachers)]

result = other_teachers_data[['Registration Number', 'Teacher Name']]
result

    Registration Number     Teacher Name
224       2024-ag-10851  Dr. Qamar Nawaz

In [5]:
df = df.drop(columns=['Semester', 'Teacher Name','Course Title','Credit Hours','Mid','Assignment','Final','Practical'])
df = df[df['Registration Number'] != '2024-ag-10851']
df.columns = df.columns.str.replace('Total', 'Marks')

In [6]:
df.head()

  Registration Number        Name Course Code  Marks Grade
0        2024-ag-5267  AMNA JAMIL     BMS-402   32.0     A
1        2024-ag-5267  AMNA JAMIL      IS-402  100.0     P
2        2024-ag-5267  AMNA JAMIL      CS-412   45.0     B
3        2024-ag-5267  AMNA JAMIL      CS-410   39.0     B
4        2024-ag-5267  AMNA JAMIL    STAT-402   30.0     C

In [7]:
df = df.pivot(
    index=['Registration Number', 'Name'], 
    columns='Course Code', 
    values=['Marks', 'Grade']
)

# This will create columns like 'Total_BMS-402', 'Grade_BMS-402', etc.
df.columns = [f"{value}_{course}" for value, course in df.columns]

df = df.reset_index()

In [8]:
df.head()

,Registration Number,Name,Marks_BMS-402,Marks_CS-406,Marks_CS-408,Marks_CS-410,Marks_CS-412,Marks_IS-402,Marks_STAT-402,Grade_BMS-402,Grade_CS-406,Grade_CS-408,Grade_CS-410,Grade_CS-412,Grade_IS-402,Grade_STAT-402
0,2024-ag-10583,MUHAMMAD DAIN SAEED,26.0,32.0,30.0,52.0,39.0,NaN,13.0,B,C,C,A,B,NaN,F
1,2024-ag-10604,LAIBA NAWAZ,29.0,50.0,48.0,49.0,54.0,92.0,48.0,B,A,A,A,A,P,A
2,2024-ag-10610,FIZZAH ISHAQ,28.0,39.0,24.0,31.0,31.0,100.0,25.0,B,B,D,C,C,P,D
3,2024-ag-10611,TALHA AMJAD,25.0,39.0,31.0,48.0,43.0,100.0,30.0,C,B,C,A,B,P,C
4,2024-ag-10613,NIDA NAVEED,11.0,27.0,22.5,9.0,7.0,100.0,30.0,F,D,F,F,F,P,C

In [9]:
df.isnull().sum()

Registration Number    0
Name                   0
Marks_BMS-402          0
Marks_CS-406           0
Marks_CS-408           0
Marks_CS-410           0
Marks_CS-412           0
Marks_IS-402           2
Marks_STAT-402         0
Grade_BMS-402          0
Grade_CS-406           0
Grade_CS-408           0
Grade_CS-410           0
Grade_CS-412           0
Grade_IS-402           2
Grade_STAT-402         0
dtype: int64

In [10]:
df['Grade_IS-402'] = df['Grade_IS-402'].fillna('P')
average_score = round(df['Marks_IS-402'].mean())

df['Marks_IS-402'] = df['Marks_IS-402'].fillna(average_score)

C:\Users\DELL Inspiron\AppData\Local\Temp\ipykernel_7292\1521996497.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Marks_IS-402'] = df['Marks_IS-402'].fillna(average_score)

In [11]:
df.isnull().sum()

Registration Number    0
Name                   0
Marks_BMS-402          0
Marks_CS-406           0
Marks_CS-408           0
Marks_CS-410           0
Marks_CS-412           0
Marks_IS-402           0
Marks_STAT-402         0
Grade_BMS-402          0
Grade_CS-406           0
Grade_CS-408           0
Grade_CS-410           0
Grade_CS-412           0
Grade_IS-402           0
Grade_STAT-402         0
dtype: int64

In [12]:
courses = [col.replace('Marks_', '') for col in df.columns if col.startswith('Marks_')]

new_order = ['Registration Number', 'Name']

for course in courses:
    new_order.extend([f'Marks_{course}', f'Grade_{course}'])

df = df[new_order]

In [13]:
df.head()

,Registration Number,Name,Marks_BMS-402,Grade_BMS-402,Marks_CS-406,Grade_CS-406,Marks_CS-408,Grade_CS-408,Marks_CS-410,Grade_CS-410,Marks_CS-412,Grade_CS-412,Marks_IS-402,Grade_IS-402,Marks_STAT-402,Grade_STAT-402
0,2024-ag-10583,MUHAMMAD DAIN SAEED,26.0,B,32.0,C,30.0,C,52.0,A,39.0,B,98.0,P,13.0,F
1,2024-ag-10604,LAIBA NAWAZ,29.0,B,50.0,A,48.0,A,49.0,A,54.0,A,92.0,P,48.0,A
2,2024-ag-10610,FIZZAH ISHAQ,28.0,B,39.0,B,24.0,D,31.0,C,31.0,C,100.0,P,25.0,D
3,2024-ag-10611,TALHA AMJAD,25.0,C,39.0,B,31.0,C,48.0,A,43.0,B,100.0,P,30.0,C
4,2024-ag-10613,NIDA NAVEED,11.0,F,27.0,D,22.5,F,9.0,F,7.0,F,100.0,P,30.0,C

In [14]:
credit_hours = {
    'BMS-402': 2,
    'CS-406': 3,
    'CS-408': 3,
    'CS-410': 3,
    'CS-412': 3,
    'IS-402': 0,
    'STAT-402': 3
}
total_credits = sum(credit_hours.values())

# For 1 Credit Hour Courses (Total 20 Marks)
qp_1_credit = {
    8: 1.00, 9: 1.50, 10: 2.00, 11: 2.33, 12: 2.67, 
    13: 3.00, 14: 3.33, 15: 3.67, 
    16: 4.00, 17: 4.00, 18: 4.00, 19: 4.00, 20: 4.00
}

# For 2 Credit Hour Courses (Total 40 Marks)
qp_2_credit = {
    16: 2.00, 17: 2.50, 18: 3.00, 19: 3.50, 20: 4.00,
    21: 4.33, 22: 4.67, 23: 5.00, 24: 5.33, 25: 5.67,
    26: 6.00, 27: 6.33, 28: 6.67, 29: 7.00, 30: 7.33, 31: 7.67, 
    32: 8.00, 33: 8.00, 34: 8.00, 35: 8.00, 36: 8.00, 
    37: 8.00, 38: 8.00, 39: 8.00, 40: 8.00
}

# For 3 Credit Hour Courses (Total 60 Marks)
qp_3_credit = {
    24: 3.00, 25: 3.50, 26: 4.00, 27: 4.50, 28: 5.00,
    29: 5.50, 30: 6.00, 31: 6.33, 32: 6.67, 33: 7.00,
    34: 7.33, 35: 7.67, 36: 8.00, 37: 8.33, 38: 8.67,
    39: 9.00, 40: 9.33, 41: 9.67, 42: 10.00, 43: 10.33,
    44: 10.67, 45: 11.00, 46: 11.33, 47: 11.67, 
    48: 12.00, 49: 12.00, 50: 12.00, 51: 12.00, 52: 12.00, 
    53: 12.00, 54: 12.00, 55: 12.00, 56: 12.00, 57: 12.00, 
    58: 12.00, 59: 12.00, 60: 12.00
}

# For 4 Credit Hour Courses (Total 80 Marks)
qp_4_credit = {
    32: 4.00, 33: 4.50, 34: 5.00, 35: 5.50, 36: 6.00,
    37: 6.50, 38: 7.00, 39: 7.50, 40: 8.00, 41: 8.33,
    42: 8.67, 43: 9.00, 44: 9.33, 45: 9.67, 46: 10.00,
    47: 10.33, 48: 10.67, 49: 11.00, 50: 11.33, 51: 11.67,
    52: 12.00, 53: 12.33, 54: 12.67, 55: 13.00, 56: 13.33,
    57: 13.67, 58: 14.00, 59: 14.33, 60: 14.67, 61: 15.00,
    62: 15.33, 63: 15.67, 64: 16.00, 65: 16.00, 66: 16.00, 
    67: 16.00, 68: 16.00, 69: 16.00, 70: 16.00, 71: 16.00,
    72: 16.00, 73: 16.00, 74: 16.00, 75: 16.00, 76: 16.00,
    77: 16.00, 78: 16.00, 79: 16.00, 80: 16.00
}

# 1. Group your dictionaries
qp_dicts = {
    1: qp_1_credit,
    2: qp_2_credit,
    3: qp_3_credit,
    4: qp_4_credit
}

# 1. Initialize a temporary running total with zeros for every student
running_total_qp = pd.Series(0.0, index=df.index)

# 2. Loop through every course
for course, credits in credit_hours.items():
    marks_col = f'Marks_{course}'
    grade_col = f'Grade_{course}'  # Now we look at the Grade column too!
    
    # Check if both columns actually exist in the dataframe to prevent errors
    if marks_col in df.columns and grade_col in df.columns:
        if credits > 0:
            # Calculate the QP for this course based on the marks
            course_qp = df[marks_col].map(qp_dicts[credits]).fillna(0.00)
            
            # --- THE NEW LOGIC ---
            # If the student's grade is 'F' or 'P', force their points to exactly 0.00
            course_qp = course_qp.mask(df[grade_col].isin(['F', 'P']), 0.00)
            
            # Add these checked points to the running total
            running_total_qp += course_qp
            
        # (If credits == 0 like IS-402, it adds 0 points automatically by skipping)

# 3. Assign the final accumulated points directly to the dataframe
df['Total_QP'] = running_total_qp

# 4. Calculate Final GPA
df['GPA'] = (df['Total_QP'] / total_credits).round(2)

df[['Registration Number', 'Name', 'Total_QP', 'GPA']].head()

  Registration Number                 Name  Total_QP   GPA
0       2024-ag-10583  MUHAMMAD DAIN SAEED     39.67  2.33
1       2024-ag-10604          LAIBA NAWAZ     67.00  3.94
2       2024-ag-10610         FIZZAH ISHAQ     34.83  2.05
3       2024-ag-10611          TALHA AMJAD     49.33  2.90
4       2024-ag-10613          NIDA NAVEED     10.50  0.62

In [15]:
df = df.drop(columns=['Total_QP'])
df.head()

,Registration Number,Name,Marks_BMS-402,Grade_BMS-402,Marks_CS-406,Grade_CS-406,Marks_CS-408,Grade_CS-408,Marks_CS-410,Grade_CS-410,Marks_CS-412,Grade_CS-412,Marks_IS-402,Grade_IS-402,Marks_STAT-402,Grade_STAT-402,GPA
0,2024-ag-10583,MUHAMMAD DAIN SAEED,26.0,B,32.0,C,30.0,C,52.0,A,39.0,B,98.0,P,13.0,F,2.33
1,2024-ag-10604,LAIBA NAWAZ,29.0,B,50.0,A,48.0,A,49.0,A,54.0,A,92.0,P,48.0,A,3.94
2,2024-ag-10610,FIZZAH ISHAQ,28.0,B,39.0,B,24.0,D,31.0,C,31.0,C,100.0,P,25.0,D,2.05
3,2024-ag-10611,TALHA AMJAD,25.0,C,39.0,B,31.0,C,48.0,A,43.0,B,100.0,P,30.0,C,2.90
4,2024-ag-10613,NIDA NAVEED,11.0,F,27.0,D,22.5,F,9.0,F,7.0,F,100.0,P,30.0,C,0.62

In [16]:
df_pre = pd.read_excel('BSCS 1St M4.xlsx', sheet_name='SEM-3', header = 1)

In [17]:
df_pre.head()

,Sr No.,Reg No.,App No.,Cnic,Name,Father Name,CS-407,Unnamed: 7,Unnamed: 8,EDU-306,...,%GPA_S3,GPA_S2,%GPA_S2,GPA_S1,%GPA_S1,CGPA,%CGPA,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,1,2024-ag-10870,10664,3310255089027,ABDUL AHAD,GHULAM NABI,33.0,C,7.00,26,...,69.25,2.1500,53.7500,2.1830,54.5750,2.37,59.25,NaN,NaN,NaN
1,2,2024-ag-10634,31,3540370426667,ABDUL REHMAN,CH MUHAMMAD SALEEM,20.5,F,0.00,20,...,23.50,1.5670,39.1750,2.8335,70.8375,1.78,44.50,NaN,NaN,NaN
2,3,2024-ag-10646,4418,3310262911571,ABDUL WAHAB AMAR,AMAR SAEED,42.0,B,10.00,26,...,84.75,3.1505,78.7625,3.3005,82.5125,3.28,82.00,NaN,NaN,NaN
3,4,2024-ag-11017,4978,3650131296239,ABDUR REHMAN,MAQSOOD UL HASSAN TARIQ,41.0,B,9.67,26,...,76.50,2.8420,71.0500,2.8165,70.4125,2.91,72.75,NaN,NaN,NaN
4,5,2024-ag-11021,15386,3310274194201,AHMAD HASSAN,MUHAMMAD AFZAL,40.0,B,9.33,26,...,80.00,3.2165,80.4125,3.4330,85.8250,3.28,82.00,NaN,NaN,NaN

In [18]:
df_pre = df_pre[['Reg No.','GPA_S1', 'GPA_S2', 'GPA_S3']]
df_pre.head()

         Reg No.  GPA_S1  GPA_S2  GPA_S3
0  2024-ag-10870  2.1830  2.1500    2.77
1  2024-ag-10634  2.8335  1.5670    0.94
2  2024-ag-10646  3.3005  3.1505    3.39
3  2024-ag-11017  2.8165  2.8420    3.06
4  2024-ag-11021  3.4330  3.2165    3.20

In [19]:
df_pre = df_pre.rename(columns={'Reg No.': 'Registration Number'})

df_pre.head()

  Registration Number  GPA_S1  GPA_S2  GPA_S3
0       2024-ag-10870  2.1830  2.1500    2.77
1       2024-ag-10634  2.8335  1.5670    0.94
2       2024-ag-10646  3.3005  3.1505    3.39
3       2024-ag-11017  2.8165  2.8420    3.06
4       2024-ag-11021  3.4330  3.2165    3.20

In [20]:
df_merged = pd.merge(df, df_pre, on='Registration Number', how='left')

df_merged.head()

,Registration Number,Name,Marks_BMS-402,Grade_BMS-402,Marks_CS-406,Grade_CS-406,Marks_CS-408,Grade_CS-408,Marks_CS-410,Grade_CS-410,Marks_CS-412,Grade_CS-412,Marks_IS-402,Grade_IS-402,Marks_STAT-402,Grade_STAT-402,GPA,GPA_S1,GPA_S2,GPA_S3
0,2024-ag-10583,MUHAMMAD DAIN SAEED,26.0,B,32.0,C,30.0,C,52.0,A,39.0,B,98.0,P,13.0,F,2.33,2.225,2.0330,1.84
1,2024-ag-10604,LAIBA NAWAZ,29.0,B,50.0,A,48.0,A,49.0,A,54.0,A,92.0,P,48.0,A,3.94,3.750,4.0000,3.80
2,2024-ag-10610,FIZZAH ISHAQ,28.0,B,39.0,B,24.0,D,31.0,C,31.0,C,100.0,P,25.0,D,2.05,2.300,2.4670,1.94
3,2024-ag-10611,TALHA AMJAD,25.0,C,39.0,B,31.0,C,48.0,A,43.0,B,100.0,P,30.0,C,2.90,2.833,2.2165,2.53
4,2024-ag-10613,NIDA NAVEED,11.0,F,27.0,D,22.5,F,9.0,F,7.0,F,100.0,P,30.0,C,0.62,3.000,2.5750,2.27

In [21]:
df_merged = df_merged.rename(columns={'GPA': 'GPA_S4'})

gpa_s4_column = df_merged.pop('GPA_S4')

df_merged['GPA_S4'] = gpa_s4_column

df_merged.head()

,Registration Number,Name,Marks_BMS-402,Grade_BMS-402,Marks_CS-406,Grade_CS-406,Marks_CS-408,Grade_CS-408,Marks_CS-410,Grade_CS-410,Marks_CS-412,Grade_CS-412,Marks_IS-402,Grade_IS-402,Marks_STAT-402,Grade_STAT-402,GPA_S1,GPA_S2,GPA_S3,GPA_S4
0,2024-ag-10583,MUHAMMAD DAIN SAEED,26.0,B,32.0,C,30.0,C,52.0,A,39.0,B,98.0,P,13.0,F,2.225,2.0330,1.84,2.33
1,2024-ag-10604,LAIBA NAWAZ,29.0,B,50.0,A,48.0,A,49.0,A,54.0,A,92.0,P,48.0,A,3.750,4.0000,3.80,3.94
2,2024-ag-10610,FIZZAH ISHAQ,28.0,B,39.0,B,24.0,D,31.0,C,31.0,C,100.0,P,25.0,D,2.300,2.4670,1.94,2.05
3,2024-ag-10611,TALHA AMJAD,25.0,C,39.0,B,31.0,C,48.0,A,43.0,B,100.0,P,30.0,C,2.833,2.2165,2.53,2.90
4,2024-ag-10613,NIDA NAVEED,11.0,F,27.0,D,22.5,F,9.0,F,7.0,F,100.0,P,30.0,C,3.000,2.5750,2.27,0.62

In [22]:
df_merged['CGPA'] = df_merged[['GPA_S1', 'GPA_S2', 'GPA_S3', 'GPA_S4']].mean(axis=1).round(2)

In [23]:
df_merged['%CGPA'] = (df_merged['CGPA'] / 4.0) * 100

df_merged['%CGPA'] = df_merged['%CGPA'].round(2)
df_merged['GPA_S1'] = df_merged['GPA_S1'].round(2)
df_merged['GPA_S2'] = df_merged['GPA_S2'].round(2)
df_merged['GPA_S3'] = df_merged['GPA_S3'].round(2)

In [24]:
df_merged.head()

,Registration Number,Name,Marks_BMS-402,Grade_BMS-402,Marks_CS-406,Grade_CS-406,Marks_CS-408,Grade_CS-408,Marks_CS-410,Grade_CS-410,...,Marks_IS-402,Grade_IS-402,Marks_STAT-402,Grade_STAT-402,GPA_S1,GPA_S2,GPA_S3,GPA_S4,CGPA,%CGPA
0,2024-ag-10583,MUHAMMAD DAIN SAEED,26.0,B,32.0,C,30.0,C,52.0,A,...,98.0,P,13.0,F,2.22,2.03,1.84,2.33,2.11,52.75
1,2024-ag-10604,LAIBA NAWAZ,29.0,B,50.0,A,48.0,A,49.0,A,...,92.0,P,48.0,A,3.75,4.00,3.80,3.94,3.87,96.75
2,2024-ag-10610,FIZZAH ISHAQ,28.0,B,39.0,B,24.0,D,31.0,C,...,100.0,P,25.0,D,2.30,2.47,1.94,2.05,2.19,54.75
3,2024-ag-10611,TALHA AMJAD,25.0,C,39.0,B,31.0,C,48.0,A,...,100.0,P,30.0,C,2.83,2.22,2.53,2.90,2.62,65.50
4,2024-ag-10613,NIDA NAVEED,11.0,F,27.0,D,22.5,F,9.0,F,...,100.0,P,30.0,C,3.00,2.58,2.27,0.62,2.12,53.00

In [25]:
student_data = df_merged[df_merged['Registration Number'] == '2024-ag-10745']

student_data

,Registration Number,Name,Marks_BMS-402,Grade_BMS-402,Marks_CS-406,Grade_CS-406,Marks_CS-408,Grade_CS-408,Marks_CS-410,Grade_CS-410,...,Marks_IS-402,Grade_IS-402,Marks_STAT-402,Grade_STAT-402,GPA_S1,GPA_S2,GPA_S3,GPA_S4,CGPA,%CGPA
22,2024-ag-10745,HAFIZ MUHAMMAD ASAD IJAZ,26.0,B,50.0,A,43.0,B,56.0,A,...,100.0,P,49.0,A,3.5,3.38,3.74,3.78,3.6,90.0

In [26]:
df_merged.to_csv('Final_Student_Results.csv', index=False)